### ISSUE TITLE
album与dialog的z-index数值关系是否考虑调整？

### ISSUE THREAD

**Issue by uuid1017** [uxcore/uxcore-album#10]
uxcore整包版本号0.17.x。

场景：在弹窗中使用图片上传组件，点击预览上传后的图片时，图片的预览出现在弹窗后面。

原因：dialog的z-index是1000
我在弹窗中使用的uploader，uploader提供了图片预览功能，调用album组件，此时预览组件时album的z-index是999。

**Comment by eternalsky** [comment]
新版已经改成 z-index 是 1000了,https://github.com/uxcore/uxcore-album/blob/master/src/Album.less#L98
