### ISSUE TITLE
希望能增加点击图片灰色背景触发关闭的API

### ISSUE THREAD

**Issue by uuid1017** [uxcore/uxcore-album#14]
业务上希望不仅是点击右上角的关闭按钮来关闭查看大图模式，也希望点击灰色背景来关闭，降低用户操作的门槛。
希望能增加一个配置项来支持此功能

**Comment by xiaowuming** [comment]
已添加点击灰色背景来关闭的功能，通过配置项“maskClosable”来控制是否开启，默认开启。
